[package]
name = "rustaria"
version = "0.1.0"
edition = "2021"

build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
gl_generator = "0.14.0"

[dependencies]
glfw = "0.43.0"
simdnoise = "3.1.6"
rectangle-pack = "0.4.2"
image = "0.23.14"
