pub const TITLE_QUOTES: [&str; 57] = ["Terraria: Dig Peon, Dig!",
"Terraria: Epic Dirt",
"Terraria: Adaman-TIGHT!",
"Terraria: Sand is Overpowered",
"Terraria Part 3: The Return of the Guide",
"Terraria: A Bunnies Tale",
"Terraria: Dr. Bones and The Temple of Blood Moon",
"Terraria: Slimeassic Park",
"Terraria: The Grass is Greener on This Side",
"Terraria: Small Blocks, Not for Children Under the Age of 5",
"Terraria: Digger T' Blocks",
"Terraria: There is No Cow Layer",
"Terraria: Suspicous Looking Eyeballs",
"Terraria: Purple Grass!",
"Terraria: No one Dug Behind!",
"Terraria: The Water Fall Of Content!",
"Terraria: Earthbound",
"Terraria: Dig Dug Ain't Got Nuthin on Me",
"Terraria: Ore's Well That Ends Well",
"Terraria: Judgement Clay",
"Terraria: Terrestrial Trouble",
"Terraria: Obsessive-Compulsive Discovery Simulator",
"Terraria: Red Dev Redemption",
"Terraria: Rise of the Slimes",
"Terraria: Now with more things to kill you!",
"Terraria: Rumors of the Guides' death were greatly exaggerated",
"Terraria: I Pity the Tools...",
"Terraria: A spelunker says 'What'?",
"Terraria: So then I said 'Something about a PC update....'",
"Terraria: May the blocks be with you",
"Terraria: Better than life",
"Terraria: Terraria: Terraria:",
"Terraria: Now in 1D",
"Terraria: Coming soon to a computer near you",
"Terraria: Dividing by zero",
"Terraria: Now with SOUND",
"Terraria: Press alt-f4",
"Terraria: I Pity the Tools",
"Terraria: You sand bro?",
"Terraria: A good day to dig hard",
"Terraria: Can You Re-Dig-It?",
"Terraria: I don't know that-- aaaaa!",
"Terraria: What's that purple spiked thing?",
"Terraria: I wanna be the guide",
"Terraria: Cthulhu is mad... and is missing an eye!",
"Terraria: NOT THE BEES!!!",
"Terraria: Legend of Maxx",
"Terraria: Cult of Cenx",
"Terraria 2: Electric Boogaloo",
"Terraria: Also try Minecraft!",
"Terraria: Also try Breath of the Wild!",
"Terraria: I just wanna know where the gold at?",
"Terraria: Now with more ducks!",
"Terraria: 9 + 1 = 11",
"Terraria: Infinite Plantera",
"Terraria: Shut Up and Dig Gaiden!",
"Terraria: Also try Don't Starve!",
];